name: CI

on:
  push:
    branches: [setup-ci]
  pull_request:
    branches: [setup-ci]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16]
    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2.1.0
        with:
          version: 6.*
          run_install: true
      - uses: actions/setup-node@v2
        with:
          node-version: 16.*
          cache: 'pnpm'
      - run: pnpm run build --if-present
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - run: pnpm run build --if-present
