name: CI

on:
  - push
  - pull_request

jobs:
  build and test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2.1.0
        with:
          version: 6.*
          run_install: true
      - name: run build
        run: pnpm run build --if-present
      - name: run test
        run: pnpm run test
