name: CI

on:
  push:
    branches: [setup-ci]
  pull_request:
    branches: [setup-ci]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        uses: actions/cache@v2
          with:
            path: ~/.pnpm-store
            key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
            restore-keys: |
              ${{ runner.os }}-
        uses: pnpm/action-setup@v2.1.0
        with:
            version: 6.*
            run_install: true
      - run: pnpm run build --if-present
