name: CI PNPM

on:
  push:
    branches: [setup-ci]
  pull_request:
    branches: [setup-ci]

jobs:
  cache-and-install:
    runs-on: ubuntu-latest

    steps:
      build:
        - uses: actions/checkout@v2

        - name: Cache pnpm modules
          uses: actions/cache@v2
          with:
            path: ~/.pnpm-store
            key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
            restore-keys: |
              ${{ runner.os }}-

        - uses: pnpm/action-setup@v2.1.0
          with:
            version: 6.*
            run_install: true
        - run: npm ci
        - run: pnpm run build --if-present
